[package]
name = "convex_hello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
convex = "0.6.0"
dotenvy = "0.15.7"
tokio = "1.36.0"
